#!/usr/bin/env python3
"""
shadow_core.py -- shared primitives for the shadow-test verification suite.

The eight shadow bases of n (coprime to 6) are
    sigma_r(n) = (-r * 24^{-1}) mod n,   r in PHI24 = {1,5,7,11,13,17,19,23}.
n passes the shadow MR test iff every sigma_r is a strong (Miller-Rabin) liar.

All other scripts in this folder import these helpers.
"""
from math import gcd

PHI24 = (1, 5, 7, 11, 13, 17, 19, 23)
M9 = 223092870  # product of the first 9 primes (2*3*5*...*23)


def is_prime(n):
    """Deterministic Miller-Rabin (correct well beyond the ranges used here)."""
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d = n - 1
    s = 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def _split(n):
    d = n - 1
    s = 0
    while d % 2 == 0:
        d //= 2
        s += 1
    return d, s


def strong_liar(a, n, d=None, s=None):
    """True iff base a is a strong Miller-Rabin liar for n (n-1 = 2^s d, d odd)."""
    if d is None:
        d, s = _split(n)
    a %= n
    if a == 0:
        return False
    x = pow(a, d, n)
    if x == 1 or x == n - 1:
        return True
    for _ in range(s - 1):
        x = x * x % n
        if x == n - 1:
            return True
    return False


def shadow_bases(n):
    """The eight shadow bases sigma_r(n) = (-r/24) mod n."""
    inv24 = pow(24, -1, n)
    return [(-r * inv24) % n for r in PHI24]


def liar_set(n):
    """Return the list of rays r for which sigma_r(n) is a strong liar."""
    if gcd(24, n) != 1:
        return []
    inv24 = pow(24, -1, n)
    d, s = _split(n)
    out = []
    for r in PHI24:
        if strong_liar((-r * inv24) % n, n, d, s):
            out.append(r)
    return out


def liar_count(n):
    return len(liar_set(n))


def is_eight_liar(n):
    return liar_count(n) == 8


def factorize(n):
    f = []
    d = 2
    while d * d <= n:
        while n % d == 0:
            f.append(d)
            n //= d
        d += 1 if d == 2 else 2
    if n > 1:
        f.append(n)
    return f


def is_carmichael(n):
    """Korselt: n squarefree, >=3 prime factors, (p-1)|(n-1) for each prime p|n."""
    if n < 561 or n % 2 == 0:
        return False
    f = factorize(n)
    if len(set(f)) != len(f) or len(f) < 3:
        return False
    return all((n - 1) % (p - 1) == 0 for p in f)


def deficiency_index(p):
    """I_p = (p-1)/L_p, L_p = order of the subgroup generated by the 8 shadow
    bases in (Z/pZ)*. In a cyclic group |<elts>| = lcm(orders)."""
    assert is_prime(p) and gcd(p, 24) == 1
    inv24 = pow(24, -1, p)
    fac = {}
    m = p - 1
    dd = 2
    while dd * dd <= m:
        while m % dd == 0:
            fac[dd] = fac.get(dd, 0) + 1
            m //= dd
        dd += 1 if dd == 2 else 2
    if m > 1:
        fac[m] = fac.get(m, 0) + 1

    def order(a):
        o = p - 1
        for q in fac:
            while o % q == 0 and pow(a, o // q, p) == 1:
                o //= q
        return o

    L = 1
    for r in PHI24:
        b = (-r * inv24) % p
        oa = order(b)
        L = L * oa // gcd(L, oa)
    return (p - 1) // L
